version: '3'

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: aurora_store
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: 111111
    ports:
      - 5432:5432

  server:

    depends_on:
      - postgres

    build: server/
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
